### PR TITLE
Repository cleanup

### PR DESCRIPTION
**Pull request by ghost**
[.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) files are only configuration files for Mac OS and thus junk files for other operating systems and the .import/ directories can be recreated so long the original files and the .import files exist.

### CODE REVIEW

**Comment by ACB-prgm** [comment]
Thanks for the effort!

**Comment by ACB-prgm** [comment]
I am confused because the .DS_Store file at the top of the directory reappeared at my last push despite that it is still in the .gitignore.  Do you know why that would happen?

**Comment by Independent-Eye2446** [comment]
Actually, I have no idea why that happened   ¯\\_(ツ)_/¯

**Comment by ACB-prgm** [comment]
I used `**/.DS_Store` instead and it seemed to do the trick!

**Pull request merged**
